
SELECT 
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT(I.USER_ID)) AS PUCHASED_USERS,
    ROUND(COUNT(DISTINCT I.USER_ID)/
          (SELECT COUNT(*) FROM USER_INFO
           WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'
           ),1) AS PUCHASED_RATIO
FROM USER_INFO I
INNER JOIN ONLINE_SALE S ON I.USER_ID = S.USER_ID
WHERE I.USER_ID IN (
    SELECT USER_ID
    FROM USER_INFO 
    WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'
)
GROUP BY YEAR, MONTH