# WITH TEMP AS (
#     SELECT 
#         *,
#         SUM(AMOUNT) AS SUMAMOUNT
#     FROM FOOD_ORDER 
#     WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
#     GROUP BY ORDER_ID
# )

# SELECT 
#     P.PRODUCT_ID,
#     P.PRODUCT_NAME,
#     SUM(P.PRICE*T.SUMAMOUNT) AS TOTAL_SALES
# FROM FOOD_PRODUCT P
# INNER JOIN TEMP T ON P.PRODUCT_ID = T.PRODUCT_ID
# GROUP BY PRODUCT_ID
# ORDER BY TOTAL_SALES DESC, PRODUCT_ID

SELECT a.PRODUCT_ID,	PRODUCT_NAME,	sum(AMOUNT*PRICE) as TOTAL_SALES
from FOOD_PRODUCT a join FOOD_ORDER b on a.PRODUCT_ID=b.PRODUCT_ID
where PRODUCE_DATE like '2022-05%'
group by PRODUCT_ID
order by TOTAL_SALES desc,a.PRODUCT_ID