WITH TEMP AS (
    SELECT 
        *,
        SUM(AMOUNT) AS SUMAMOUNT
    FROM FOOD_ORDER 
    WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
    GROUP BY ORDER_ID
)

SELECT 
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(P.PRICE*T.SUMAMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P
INNER JOIN TEMP T ON P.PRODUCT_ID = T.PRODUCT_ID
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID
