WITH TEMP AS (SELECT 
    MEMBER_ID
FROM REST_REVIEW 
GROUP BY MEMBER_ID
ORDER BY COUNT(*) DESC
LIMIT 1 )

SELECT 
    MEMBER_NAME,
    REVIEW_TEXT,
    DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE M
INNER JOIN REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID
INNER JOIN TEMP T ON M.MEMBER_ID = T.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT

